version: "3"

services:
  web_app_image:
    container_name: web_app_image
    build:
      context: ./
      #dockerfile: ./Dockerfile
    volumes:
     - ../code/:/var/www/html/UI/
    tty: true
    image: web_app_image:latest
    # restart: always
    ports:
      - "80:80"